[package]
name = "hackrf_node"
version = "0.1.0"
edition = "2021"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futuresdr = { path = "../.." }
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.28"
