[package]
name = "zigbee"
version = "0.0.1"
edition = "2021"
default-run = "rx"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rx"
path = "src/bin/rx.rs"

[[bin]]
name = "trx"
path = "src/bin/trx.rs"

[[bin]]
name = "tx"
path = "src/bin/tx.rs"

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futuresdr = { path = "../..", features = ["soapy"] }
clap = { version = "3.1.18", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futuresdr = { path = "../.." }
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"