[package]
name = "perf-zynq"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = "3.1.0"
futuresdr = { path = "../..", features = ["zynq"] }
log = { version = "0.4", features = ["release_max_level_off"] }
rand = "0.8.0"

[[bin]]
name = "zynq"
path = "zynq.rs"
