[package]
name = "buffer_size"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = "3.1.0"
futuresdr = { path = "../..", features = ["flow_scheduler"] }
log = { version = "0.4", features = ["release_max_level_off"] }

[[bin]]
name = "buffer_size"
path = "buffer_size.rs"
