[package]
name = "null_rand_latency"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.0"
futuresdr = { path = "../..", features = ["flow_scheduler", "tpb_scheduler", "lttng"] }
log = { version = "0.4", features = ["release_max_level_off"] }

[[bin]]
name = "null_rand_latency"
path = "null_rand_latency.rs"
